package com.davidkazad.chantlouange.utils;

public class catt {

    public String[] getTitle() {
        return new String[]{
                "Grand Dieu, nous te bénissons",
                "Je chanterai , Seigneur , tes œuvres magnifiques",
                "Gloire, gloire à l’ Eternel ! ",
                "Je veux chanter , louer mon Dieu, ",
                "Jésus, Jésus, Jésus, Jésus ",
                "A Dieu soit la gloire ! ",
                "Dans mon bonheur immense ",
                "Le nom de Jésus est si doux ! ",
                "Christ est ressuscité ",
                "Du rocher de Jacob ",
                "Adorable mystère",
                "Trois fois saint Jéhovah !(bis)",
                "Oh ! loué soit ton nom , Sauveur plein de tendresse ",
                "Toi, le Fils éternel , toi, bien-aimé du Père",
                "Oui, ton amour est un amour sublime",
                "Devant mon âme confondue ",
                "A celui qui nous a lavé ",
                "Vers toi monte notre hommage",
                "Mon Sauveur souffrit sur la croix",
                "Oh! bonheur de te connaîtr ",
                "Nous adorons. Toi que notre cœur aime. ",
                "Je l’ai trouvé, je l’ai trouvé ",
                "Il faut, grand Dieu ! Que de mon cœur ",
                "Par tous saints glorifiés",
                "Chantons du sauveur la tendresse :",
                "Bénissons Dieu par nos cantiques",
                "Les rayons de l’amour divin ",
                "Etre à tes pieds, comme Marie,",
                "Oh ! que toute la terre  entonne ",
                "Rédempteur adorable",
                "Ma richesse, ma gloire ",
                "Portant sa croix, il monte ",
                "Jésus divin modele, ",
                "M’aimant...quand la route est obscure ",
                "Jésus est notre ami suprême:",
                "L’amour éternel, insondable ",
                "Ah! si ton sang, si ta mort, si ta Vie",
                "Au pied de ta croix prosterné, ",
                "O Christ ! quelle immense douleur,",
                "Dans les cieux et sur la terre, ",
                "Jésus, Agneau de Dieu ! du sang de l’alliance ",
                "Jésus sort de la tombe ;",
                "Tu m’as aimé, seigneur avant que la lumière ",
                "Roi couvert de blessures,",
                "Agneau de Dieu, Messager de la grâce ",
                "Jésus-Christ est ma sagesse,",
                "A toi la gloire, ",
                "Venez contempler  au calvaire ",
                "En contemplant la croix  Bénie ",
                "Viens mon âme ! et contemple ",
                "C’est toi, Jésus, Pain de vie, ",
                "Obscur et pauvre au monde présenté",
                "Rien, ô Jésus ! que ta grâce, ",
                "Jésus t’appelle, oh ! viens et vois, ",
                "Vous qui marchez dans la souillure, ",
                "Attire, ô Sauveur, attire, ",
                "Souviens-toi du calvaire, ",
                "Entends-tu ? Jésus t’appelle ;",
                "De Jésus, entends-tu la voix,",
                "Nous ne sommes plus esclaves ;",
                "Il est un ami suprême : ",
                "Viens à la croix, âme perdue,",
                "Où va cette foule empressée, ",
                "Bien loin de toi, mon Père, ",
                "O vous qui n’avez pas paix,",
                "Le maître est là qui t’appelle ; ",
                "Où trouver une retraite, ",
                "Ecoute de Dieu la parole, ",
                "Pourquoi donc attendre, mon frère ? ",
                "Toi dont l’âme est tourmentée ",
                "Gémissant sous l’esclavage, ",
                "Viens, viens à Jésus ! ",
                "Voici Jésus, notre sauveur ",
                "Oh ! croyez que Dieu vous donne ",
                "Cœurs fatigués et lassés du péché, ",
                "Reviens ! reviens ! ",
                "Possèdes-tu, pauvre pécheur, ",
                "A Golgotha, l’Agneau sans tâche ",
                "Arrête, ô pécheur, arrête ! ",
                "comme un phare sur la plage, ",
                "Le péché qui t’accable ",
                "Reviens à ton Père, ",
                "Il va finir, le beau jour de la grâce",
                "Il est un roc séculaire, ",
                "O, toi qui souffre solitaire, ",
                "Aujourd’hui, Jesus t’appelle, ",
                "Regarde, âme angoissée, au mourant du Calvaire",
                "On frappe !on frappe !entends-tu ? ",
                "Nous voguons vers un beau rivage",
                "Viens à Jesus, il t’appelle ; ",
                "Venez au sauveur qui vous aime, ",
                "C’est encore temps! à la gloire éternelle",
                "Loin du sauveur, pourquoi, mon frère, ",
                "Demain, peut-être, ",
                "Viens, âme perdue,",
                "Tous mes péchés, (bis) ",
                "Sans un Dieu sauveur pour Père, ",
                "Vous tous dont l’âme est envahie ",
                "Par ce chemin solitaire,",
                "Dix milles milliers sont entrés, ",
                "Mortel, voulez-vous savoir ",
                "Ecoutez la bonne nouvelle, ",
                "Nous voulons marcher vers le ciel : ",
                "Comme un doux murmure, ",
                "Si vous saviez quel sauveur je possède ! ",
                "A la croix, où mourut mon sauveur, ",
                "Viens au père qui t’appelle, ",
                "Pécheur ! Vous venez d’entendre, ",
                "Bientôt le seigneur  va venir ! ",
                "Pécheur, je voudrai te guérir ; ",
                "Le prince de la vie ",
                "Une bonne nouvelle ",
                "Es-tu lassé rempli de tristesse ?...",
                "Rien ne peut sauver mon âme ",
                "Voudrais-tu goûter le parfait bonheur ? ",
                "Publiez bien haut la grande nouvelle : ",
                "Jésus frappe à votre porte : ",
                "Oh ! Viens à Moi ton Sauveur et ton Frère, ",
                "O pécheur hésitant, ",
                "Où cherchez-vous le bonheur ? ",
                "Pauvre enfant, au bord de l’abîme ! ",
                "O mon Dieu dans ma souffrance, ",
                "Pécheurs, voyez l’Agneau du Père ",
                "Tel que je suis, précheur rebelle,",
                "Jésus, par ton sang précieux, ",
                "J’ai trouvé, j’ai trouvé le Dieu que je réclame ! ",
                "Source feconde, ",
                "O jour heureux, jour de bonheur, ",
                "Tel que je suis, sans rien en moi, ",
                "J’ai longtemps erré sans guide, ",
                "Roc séculaire, ",
                "Joie au ciel ! Ecoutez, écoutez ces cantiques:",
                "Seigneur ta grâce m’appelle, ",
                "Bienheureux, pardonné, je benis et j’adore...",
                "suis sauvé ! Dieu m’a fait grâce. ",
                "Miséricorde insondable ! ",
                "Torrents d’amour et de grâce, ",
                "Seigneur Jesus ! je viens à toi ! ",
                "Aujourd’hui tu m’appelles, ",
                "Veux-tu briser du péché le pouvoir? ",
                "Il m’a sauvé, il m’a sauvé, ter ",
                "Seigneur ! du sein de la poussière, ",
                "O Seigneur, benie la parole ",
                "Pour triompher dans les combats, ",
                "Romps-nous le pain de vie",
                "A tes pieds ,ô divin Maître ! ",
                "Oh !que ton joug est facile ! ",
                "Mon âme en silence ",
                "Comme une terre altérée, ",
                "O DIEU de vérité pour qui seul je soupire  ",
                "Que ta lumière, ",
                "Déjà l’étoile ",
                "Que la grâce de notre Seigneur Jésus-Christ, ",
                "Jésus, ta sainte présence ",
                "Seigneur, ce que je réclame, ",
                "Jésus est au milieu de nous, ",
                "Toi qui disposes ",
                "Grâce infinie ! ",
                "Ecoute l’appel du Berger ! ",
                "Ah ! que je ne sois pas comme un rameau stérile. ",
                "Un regard sur ta croix sanglante, ",
                "Divin Sauveur, toi qui vins sur la terre ",
                "Je le connais, celui qui donne ",
                "Qu’il fait bon à ton service,",
                "C’est mon joyeux service ",
                "Ma vie enfin je te donne, ",
                "Précieux Jésus, je t’aime. ",
                "Jésus, je te suivrai partout. ",
                "A toi mon Dieu, je m’abandonne. ",
                "Seigneur ! sanctifie ",
                "Entre tes mains j’abandonne ",
                "Au pied de la croix sanglante. ",
                "Je m’approche de toi. ",
                "Seul refuge de mon âme. ",
                "L’amour de Jésus-Christ nous presse:",
                "Oui, Jésus, c’est vers Toi. ",
                "Ah ! donne à mon âme ",
                "Que tout genou fléchisse. ",
                "Jésus, Jésus mon sauveur. ",
                "La voix du Seigneur m’appelle : ",
                "J’entends ta douce voix. ",
                "Enfin Jésus a triomphé ",
                "Mon âme est libéré ",
                "viens !mon ame-Te réclame, ",
                "Seigneur à ton regard de flamme",
                "Jesus,aujourd’hui m’appelle, ",
                "C’est un rempart que notre Dieu, ",
                "Plus que vainqueurs, telle est notre dévise. ",
                "La croix reste debout, Alleluia !Alléluia ! ",
                "Il est une sainte guerre, ",
                "Jusqu’à la mort nous te serons fidèles ; ",
                "Plus le mal est présent, plus ma misère est grande, ",
                "Le signal de la victoire ",
                "Sans attendre, je veux tendre ",
                "Qui me relève dans ma chute ?",
                "Notre Chef et Maître, c’est le Roi des rois ; ",
                "Tes saints dans la lutte, ",
                "Debout pour la sainte guerre ! ",
                "Non, nous ne saurions nous taire ",
                "Veille au matin, quand un ciel sans nuage",
                "A celui qui sera vainqueur. ",
                "Vous qui gardez les murs de la sainte cité,",
                "« Sentinelle vigilante,",
                "Debout, sainte cohorte,",
                "Revêtons notre armure ",
                "Travaillons et luttons ! Nous sommes au Seigneur,",
                "Viens âme qui pleures, ",
                "Maître, entends-tu la tempête",
                "Quand le vol de la tempête",
                "Pour toi qu’un tourment oppresse. ",
                "Une nacelle en silence",
                "Pour moi chrétien, la terre est un exil ;",
                "La croix que Dieu me donne ",
                "« Invoque-moi du sein de la détresse :",
                "Reste avec nous, Seigneur, le jour décline. ",
                "Aussi longtemps qu’étranger sur la terre. ",
                "Oh ! quelle paix parfaite ",
                "Quand ma route est obscure ",
                "Ton beau nom calme et console, ",
                "Quel autre au ciel si-je que toi ? ",
                "Mort avec Christ d'une mort volontaire, ",
                "Dans ce triste monde je ne puis vivre, ",
                "Oh ! Quel repos quand le mal m’environne ",
                "Tiens dans ta main, ta main puissante et forte,",
                "Que ton fidèle amour est une grande chose,",
                "A Jésus je m’abandonne ; ",
                "Comme un fleuve immense,",
                "O fils de Dieu, mon Sauveur bien-aimé ! ",
                "Ne crains rien, je t'aime !",
                "Paix ! douce paix ! et mes nombreux péchés ? ",
                "Oh ! le meilleur ami, c’est Jésus ! ",
                "Jamais Dieu ne délaisse ",
                "Un chrétien je croyais être ",
                "Non, rien en ma personne, ",
                "Quand je craindrai sur la route, ",
                "Je ne sais pourquoi, dans sa grâce,",
                "Quel ami fidèle et tendre ",
                "Tant qu’il vit, tant qu’il règne, ",
                "Ô jour béni, jour de victoire ",
                "Aux jours d'angoisse et de souffrance, ",
                "Oui, selon ta promesse,",
                "Sur toi, Sauveur, qui se fonde, ",
                "Brillante Étoile, Étoile du matin,",
                "Saisis ma main craintive ",
                "Mon salut, ma nourriture, ",
                "Quel repos céleste, Jésus, d'être à Toi !",
                "Refrain :",
                "Mon Dieu, plus près de toi, ",
                "C'est à l'ombre de tes ailes",
                "Pour toi seul en qui j’espère, ",
                "Conduis-nous sûrement, ô divin Sauveur ! ",
                "J'ai soif de ta présence,",
                "Ecoutez, petits et grands,",
                "Ici pleurer et souffrir,",
                "Voir mon Sauveur face à face,",
                "La trompette a retenti :",
                "Il va venir, le Seigneur que j'adore ;",
                "Or, vers minuit, se fit entendre /n Un cri disant : « voici l’Epoux ! »/n C’est Jésus !voyez-le descendre !/n Autour de lui rallions-nous./n  ",
                "Dans la patrie éternelle ",
                "Je ne sais pas le jour où je verrais mon Roi,",
                "Oh ! viens, Seigneur Jésus !ta divine présence ",
                "Sainte Sion, ô patrie éternelle ! ",
                "Oh ! quand sera-ce, fils de Dieu, ",
                "Oh ! quel beau jour, où, devant ta face,",
                "Il vient bientôt remporter la victoire. ",
                "Quel bonheur ! Jesus vient !sa voix se fait entendre ; ",
                "Avec allégresse",
                "Vers le ciel, vers le ciel,",
                "Dans le ciel, séjour de la gloire, ",
                "Bientôt Seigneur, tu reviendras ! ",
                "Pèlerin sur cette terre,",
                "Là-haut, là-haut dans la maison du Père, ",
                "Il est un espoir, qui toujours soulage ",
                "Le temps s’envole et nous emporte, ",
                "Connais-tu cette cité,",
                "Contempler mon Dieu sur son trône,",
                "Au ciel est la maison du Père, ",
                "Nous attendons le Sauveur glorieux ",
                "Consolez vos cœurs qui pleurent, ",
                "Avançons-nous joyeux, toujours  joyeux, ",
                "",
                "Béni soit le lien ",
                "Ah! qu’il est beau de voir des frères ",
                "Tu nous combles de bien Seigneur ! ",
                "O Dieu, nous le plaçons sous ta main paternelle, ",
                "Seigneur Jésus ! une vaste carrière ",
                "Qu’ils sont beaux sur les montagnes ",
                "O Seigneur, Eternel ! une nouvelle année, ",
                "Jésus soit avec vous à jamais !",
                "si le temps fuit ? si l’heure sonne ? ",
                "Seigneur, que la terre entière",
                "Alléluia ! Jésus sort de la tombe, ",
                "Ô toi, Seigneur Jésus, intarissable source",
                "Seigneur Jésus ! Bon Berger ",
                "Suivez, suivez l'Agneau jusqu'au soir de la vie ;",
                "Tout joyeux bénissons le Seigneur,",
                "Je suis petit, mais de mon âge,",
                "Nul enfant n'est trop petit ",
                "Au petit, ",
                "Jésus est mon, puissant Sauveur, ",
                "Bientôt Jésus va nous prendre,",
                "« Je suis la lumière »,",
                "O pèlerin de la Ville d’or ! ",
                "Bon Sauveur, berger fidèle,",
                "Le Seigneur m'aime,",
                "Sous le sang, le précieux sang, ",
                "Jésus quitta le trône de son Père",
                "Jésus me demande d'être",
                "Chaque jour de ma vie,",
                "Il est un pays magnifique,",
                "Dès aujourd’hui je veux aimer ",
                "Jésus ne change pas, ",
                "David n'avait rien que sa fronde",
                "Oh ! que ta main paternelle",


        };
    }
}
